github_org_dict:
  {
    "NHSX": "nhsx",
    "NHS 111 Online - NHS Digital": "111Online",
    "NHS Digital": "nhsdigital",
    "NHS Connect": "nhsconnect",
    "NHS England": "nhsengland",
    "NHS Python Community for Healthcare": "nhs-pycom",
    "NHS-R Community": "nhs-r-community",
    "NHS.UK": "nhsuk",
    "NHSE-NDRS": "NHSE-NDRS",
    "Public Health England": "publichealthengland",
    "Nottinghamshire Healthcare NHS Foundation Trust - CDU Data Science Team": "CDU-data-science-team",
    "NHS Midlands and Lancashire CSU - The Strategy Unit": "the-strategy-unit",
    "University of Oxford - Evidence-Based Medicine Data Lab": "ebmdatalab",
    "OpenSAFELY Studies": "opensafely",
    "OpenSAFELY Core": "opensafely-core",
    "The Health Foundation Analytics Lab": "HFAnalyticsLab",
    "NHS BNSSG Analytics": "nhs-bnssg-analytics",
    "BHF Data Science Centre": "BHFDSC",
    "NHS Leadership Academy": "NHSLeadership",
    "NICE Digital": "nice-digital",
    "North Central London ICB": "ncl-icb-analytics",
    "Birmingham and Solihull ICS": "Birmingham-and-Solihull-ICS",
    "UK Health Security Agency": "ukhsa-collaboration",
    "GIG Cymru - NHS Wales": "GIG-Cymru-NHS-Wales"
  }

gitlab_group_dict: { "NHS Business Services Authority": "2955125" }

github_tag_lst:  ["nhs",
                  "rap",
                  "nhs",
                  "machine-learning",
                  "synthetic",
                  "simulation",
                  "date",
                  "full_name",
]
